spring:
  logging:
    level:
      root: DEBUG
  datasource:
    url: jdbc:h2:mem:bdw2025
    username: sa
    password: sa
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false